const express = require("express");
const dotenv = require("dotenv");
const path = require("path");
const cors = require("cors");
const envPath = path.resolve(__dirname, '.env');
dotenv.config({ path: envPath });
const db = require("./app/models");
const app = express();
app.use(cors({ origin: "http://localhost:42221", methods: "GET,HEAD,PUT,PATCH,POST,DELETE" }));
app.use(express.json());
db.sequelize.sync({ alter: true }).then(() => console.log("✅ Database & tables synced successfully."));
const authRoutes = require("./app/routes/auth.routes");
const bookRoutes = require("./app/routes/book.routes");
app.get("/", (req, res) => res.json({ message: "Welcome to Book Management API with MySQL & JWT." }));
app.use("/api/auth", authRoutes);
app.use("/api/books", bookRoutes);
const PORT = process.env.PORT || 3000;
app.listen(PORT, () => console.log(`🚀 Server running on http://localhost:${PORT}`));
